language: rust
cache: cargo

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: BENCHES=true
    - rust: 1.36.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y binutils-dev libunwind8-dev

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features rand,all-languages
  - cargo test --verbose --features rand,all-languages
  # benchmarks
  - if [[ $TRAVIS_RUST_VERSION == "nightly" && ${BENCHES} ]]; then cargo bench --verbose --features rand; fi
  - if [[ $TRAVIS_RUST_VERSION == "nightly" && ${BENCHES} ]]; then cargo bench --verbose --features rand,japanese; fi
